sudo: required

language: python

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker --version
  - docker build -t py-libre-office .
  - docker tag py-libre-office $DOCKER_USERNAME/py-libre-office
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/py-libre-office:latest
