name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u "${{ secrets.DOCKER_USER }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build & push
        env:
          CONTAINER_IMAGE: ${{ secrets.DOCKER_USER }}/py-libre-office:6.4.7.2-python3.8.5
        run: |
          docker build -t $CONTAINER_IMAGE .
          docker push $CONTAINER_IMAGE
